apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: jaeger
      labels:
        app: jaeger
        app.kubernetes.io/name: jaeger
        app.kubernetes.io/component: all-in-one
    spec:
      replicas: 1
      strategy:
        type: Recreate
      selector:
        matchLabels:
          app: jaeger
      template:
        metadata:
          labels:
            app: jaeger
            app.kubernetes.io/name: jaeger
            app.kubernetes.io/component: all-in-one
        spec:
          containers:
            -   image: jaegertracing/all-in-one
                name: jaeger
                ports:
                  - containerPort: 6831
                    protocol: UDP
                  - containerPort: 6832
                    protocol: UDP
                  - containerPort: 16686
                    protocol: TCP
                readinessProbe:
                  httpGet:
                    path: "/"
                    port: 14269
                  initialDelaySeconds: 5
  - apiVersion: v1
    kind: Service
    metadata:
      name: jaeger-query
      labels:
        app: jaeger
        app.kubernetes.io/name: jaeger
        app.kubernetes.io/component: query
    spec:
      ports:
        - name: query-http
          port: 80
          protocol: TCP
          targetPort: 16686
      selector:
        app.kubernetes.io/name: jaeger
        app.kubernetes.io/component: all-in-one
      type: NodePort
  - apiVersion: v1
    kind: Service
    metadata:
      name: jaeger-grpc
      labels:
        app: jaeger
        app.kubernetes.io/name: jaeger
        app.kubernetes.io/component: query
    spec:
      ports:
        - name: query-grpc
          port: 80
          protocol: TCP
          targetPort: 16685
      selector:
        app.kubernetes.io/name: jaeger
        app.kubernetes.io/component: all-in-one
      type: NodePort
  - apiVersion: v1
    kind: Service
    metadata:
      name: jaeger-agent-svc
      labels:
        app: jaeger
        app.kubernetes.io/name: jaeger
        app.kubernetes.io/component: agent
    spec:
      ports:
        - name: agent-compact
          port: 6831
          protocol: UDP
          targetPort: 6831
        - name: agent-binary
          port: 6832
          protocol: UDP
          targetPort: 6832
      selector:
        app.kubernetes.io/name: jaeger
        app.kubernetes.io/component: all-in-one
      type: NodePort
