---
apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  name: krustlet2
  namespace: kube-node-lease
spec:
  holderIdentity: krustlet2
  leaseDurationSeconds: 40
  renewTime: "2022-06-19T12:27:28.521941Z"

---
apiVersion: v1
kind: Service
metadata:
  name: krustlet2
  labels:
    app: krustlet2
spec:
  ports: []
  clusterIP: None
  selector:
    app: krustlet2

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: krustlet2
spec:
  selector:
    matchLabels:
      app: krustlet2
  serviceName: krustlet2
  replicas: 1
  template:
    metadata:
      labels:
        app: krustlet2
    spec:
      automountServiceAccountToken: false
      nodeName: k3s-worker2
      terminationGracePeriodSeconds: 10
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: NotIn
                    values:
                      - 'true'
      containers:
        - name: krustlet
          image: localhost:32000/krustlet:latest
          imagePullPolicy: Always
          ports: []
          args:
          - --node-name=krustlet2
          - --insecure-registries=docker-registry.default.svc.cluster.local:5000
          - --node-ip=192.168.0.2
          - --hostname=krustlet2
          - --enable-telemetry=true
          - --max-pods=100
          env:
            - name: OTEL_EXPORTER_JAEGER_AGENT_HOST
              value: jaeger-agent-svc.default.svc.cluster.local
            - name: OTEL_EXPORTER_JAEGER_AGENT_PORT
              value: '6831'
            - name: RUST_LOG
              value: info,regalloc=warn
          resources:
            requests:
              cpu: 1900m
              memory: 7000Mi
            limits:
              cpu: 1900m
              memory: 7000Mi
