apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- plugin.yaml

patchesJson6902:
- target:
    group: argoproj.io
    version: v1alpha1
    kind: ExecutorPlugin
    name: wasm
  path: image.json
