apiVersion: argoproj.io/v1alpha1
kind: ExecutorPlugin
metadata:
  name: wasm
  namespace: argo-workflows
spec:
  sidecar:
    container:
      image: ghcr.io/shark/wasm-workflows-plugin:v0.3.0
      name: wasm-workflows-plugin
      ports:
      - containerPort: 3000
      livenessProbe:
        httpGet:
          path: /healthz
          port: 3000
        initialDelaySeconds: 2
        periodSeconds: 1
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532 # nonroot
      resources:
        limits:
          cpu: 1024m
          memory: 1024Mi
        requests:
          cpu: 1024m
          memory: 512Mi
      env:
      - name: LOG_LEVEL
        value: debug
      - name: MODE
        value: local
#      - name: INSECURE_OCI_REGISTRIES
#        value: 192.168.64.2:32000
#      - name: OTEL_ENABLE
#        value: '1'
#      - name: OTEL_EXPORTER_JAEGER_AGENT_HOST
#        value: jaeger-agent-svc.default.svc.cluster.local
#      - name: OTEL_EXPORTER_JAEGER_AGENT_PORT
#        value: '6831'
