apiVersion: argoproj.io/v1alpha1
kind: ExecutorPlugin
metadata:
  name: wasm
  namespace: argo-workflows
spec:
  sidecar:
    container:
      image: ghcr.io/shark/wasm-workflow-executor:v0.1.0
      name: wasm-workflow-executor
      ports:
      - containerPort: 3000
      livenessProbe:
        httpGet:
          path: /healthz
          port: 3000
        initialDelaySeconds: 2
        periodSeconds: 1
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532 # nonroot
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
