[package]
name = "wasm-workflow-executor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1.30"
tracing-subscriber = { version = "0.3.8", features = ["env-filter"] }

tokio = { version = "1.17.0", features = ["full"] }
serde = { version = "1.0.136", features = ["derive"] }
tower-http = { version = "0.2.2", features = ["trace"] }

axum = "0.4.5"
