[package]
name = "workflow-model"
version = "0.1.0"
edition = "2021"

[features]
host = ["dep:tempfile"]
plugin = []

[dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tempfile = { version = "3", optional = true }
