[package]
name = "workflow-model"
version = "0.1.0"
edition = "2021"

[features]
host = ["dep:tempfile"]
plugin = []

[dependencies]
anyhow = "1.0.57"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
tempfile = { version = "3.3.0", optional = true }
