apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: wasm-
spec:
  entrypoint: wasm
  arguments:
    parameters:
      - name: text
        value: Hello World
  templates:
    - name: wasm
      inputs:
        parameters:
          - name: text
      plugin:
        wasm:
          module:
            oci: ghcr.io/shark/wasm-workflows-plugin-example-ferris-says:latest
