apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: wasm-
spec:
  entrypoint: steps
  arguments:
    parameters:
      - name: url
        value: https://ip4only.me/api/
  templates:
    - name: steps
      steps:
      - - name: wasm1
          template: wasm-http
          arguments:
            parameters:
            - name: url
              value: '{{workflow.parameters.url}}'
        - name: wasm2
          template: wasm-http
          arguments:
            parameters:
            - name: url
              value: '{{workflow.parameters.url}}'
        - name: wasm3
          template: wasm-http
          arguments:
            parameters:
            - name: url
              value: '{{workflow.parameters.url}}'
    - name: wasm-http
      inputs:
        parameters:
          - name: url
      plugin:
        wasm:
          module:
            oci: ghcr.io/shark/wasm-workflows-plugin-http-request:latest
          permissions:
            http:
              allowed_hosts:
                - https://ip4only.me
