apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: wasm-
spec:
  entrypoint: wasm
  arguments:
    parameters:
      - name: url
        value: https://ip4only.me/api/
  templates:
    - name: wasm
      inputs:
        parameters:
          - name: url
      plugin:
        wasm:
          module:
            oci: ghcr.io/shark/wasm-workflows-plugin-http-request:latest
          permissions:
            http:
              allowed_hosts:
                - https://ip4only.me
