apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: wasm-
spec:
  entrypoint: wasm
  arguments:
    parameters:
    - name: effect
      value: desaturate
    artifacts:
      - name: input
        s3:
          key: IMG_5994.jpg
  templates:
  - name: wasm
    inputs:
      parameters:
      - name: effect
      artifacts:
      - name: input
        path: /input.jpg
    plugin:
      wasm:
        module:
          oci: ghcr.io/shark/wasm-workflows-plugin-image-processor:latest
