apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: image-processor-container-
spec:
  entrypoint: process

  arguments:
    parameters:
    - name: effect
      value: desaturate
    artifacts:
      - name: input
        s3:
          key: IMG_5994.jpg
  templates:
  - name: process
    inputs:
      parameters:
      - name: effect
      artifacts:
      - name: input
        path: /work/artifacts-in/input
    container:
      image: 192.168.64.2:32000/container-image-processor
      command: [image-processor]
      env:
      - name: OTEL_ENABLE
        value: '1'
      - name: OTEL_EXPORTER_JAEGER_AGENT_HOST
        value: jaeger-agent-svc.default.svc.cluster.local
      - name: OTEL_EXPORTER_JAEGER_AGENT_PORT
        value: '6831'
    outputs:
      artifacts:
      - name: output
        path: /work/artifacts-out/output
