record parameter {
  name: string,
  value-json: string
}

record invocation {
  workflow-name: string,
  plugin-options: list<parameter>,
  parameters: list<parameter>,
}

record node {
  phase: string,
  message: string,
  parameters: list<parameter>,
}

invoke: function(ctx: invocation) -> node
