apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: wasm-
spec:
  entrypoint: wasm
  arguments:
    parameters:
    - name: text
      value: https://github.com/Shark/wasm-workflows-plugin
  templates:
  - name: wasm
    inputs:
      parameters:
      - name: text
    plugin:
      wasm:
        module:
          oci: ghcr.io/shark/wasm-workflows-plugin-example-text2qr:latest
