name: Build the container image
on:
  workflow_call:
    outputs:
      version:
        description: Container Image Version
        value: ${{ jobs.build.outputs.version }}
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.tag.outputs.tag }}
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker Layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - uses: actions/checkout@v2

    - name: Get tag
      id: tag
      run: echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"

    - name: docker build
      uses: docker/build-push-action@v2
      with:
        tags: sh4rk/wasm-workflow-executor:${{ steps.tag.outputs.tag }}
        outputs: type=docker,dest=/tmp/container-image.tar
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new

    - name: Compress the image
      run: bzip2 /tmp/container-image.tar

    # Temp fix
    # https://github.com/docker/build-push-action/issues/252
    # https://github.com/moby/buildkit/issues/1896
    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache

    - name: Store the image an artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: container-image
        path: /tmp/container-image.tar.bz2
        retention-days: 7
