name: Check the code
on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install latest nightly toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: rustfmt, clippy

    - uses: Swatinem/rust-cache@f8f67b7515e98e4ac991ccb5c11240861e0f712b # https://github.com/Swatinem/rust-cache/tree/v1

    - name: cargo check
      uses: actions-rs/cargo@v1
      with:
        command: check

    - name: cargo clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy

    - name: cargo fmt
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --check
