name: Release on tag
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    uses: ./.github/workflows/build-container-image.yml
  publish:
    uses: ./.github/workflows/publish-container-image.yml
    needs: [build]
    with:
      version: ${{ needs.build.outputs.version }}
  changelog:
    uses: ./.github/workflows/create-changelog.yml
  executor_plugin:
    uses: ./.github/workflows/create-executor-plugin.yml
    needs: [publish]
    with:
      container_image: ${{ needs.publish.outputs.container_image }}
  release:
    runs-on: ubuntu-latest
    needs: [publish, changelog, executor_plugin]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: repo
        fetch-depth: 0

    - name: Download executor plugin artifact
      uses: actions/download-artifact@v3
      with:
        name: argo-executor-plugin
        path: argo-executor-plugin

    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        draft: false
        prerelease: true
        name: Release ${{ needs.changelog.outputs.tag }}
        tag_name: ${{ needs.changelog.outputs.tag }}
        body: |
          # Usage

          Installing the plugin is simple.

          Ensure that you enabled executor plugins [as described in Argo Workflows' documentation](https://argoproj.github.io/argo-workflows/executor_plugins/).

          Copy the URL to the Executor Plugin configuration from this release and apply it with `kubectl`:

          ```
          kubectl apply -f https://github.com/Shark/wasm-workflows-plugin/releases/download/${{ needs.changelog.outputs.tag }}/wasm-executor-plugin-configmap.yaml
          ```

          That's all you need to submit a workflow with a Wasm module. You can use our example:

          ```
          kubectl create -f https://raw.githubusercontent.com/Shark/wasm-workflows-plugin/67ae607ec65e1ac93bc1749c5f7a9bde4b673cfd/wasm-modules/examples/ferris-says/workflow.yaml
          ```

          That's it. :sparkles:

          # Changelog

          ${{ needs.changelog.outputs.changelog }}
        files: argo-executor-plugin/wasm-executor-plugin-configmap.yaml
